services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '6500:5432'
    volumes:
      - progresDB:/data/postgres
    env_file:
      - ./app.env
    healthcheck:
      interval: 20s
      timeout: 20s
      retries: 5

  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    env_file:
      - ./app.env
    ports:
      - "5050:80"
  app:
    build: ./
    container_name: banners_service
    ports:
      - "8000:8000"
    depends_on:
      - postgres 


  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON=/api/api.yaml
      - BASE_URL=/swagger
  volumes:
    - ./api:/api
    
volumes:
  progresDB:

networks:
  default:
      driver: bridge