services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '6500:5432'
    volumes:
      - progresDB:/data/postgres
    env_file:
      - ./app.env
    healthcheck:
      interval: 20s
      timeout: 20s
      retries: 5

  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    env_file:
      - ./app.env
    ports:
      - "5050:80"
  app:
    build: ./
    container_name: banners_service
    ports:
      - "8000:8000"
    depends_on:
      - postgres 
    
volumes:
  progresDB:

networks:
  default:
      driver: bridge